volumes:
  psql-tbh:
services:
  psql:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dfsjhkdswkjntelsmldbfvsgknl5t
    volumes:
      - psql-tbh:/var/lib/postgresql/data
    ports:
      - 5554:5432